import Image from "next/image";
import Link from "next/link";
import Container from "@/components/ui/Container";
import SectionLabel from "@/components/ui/SectionLabel";
import ButtonLink from "@/components/ui/ButtonLink";
import SignatureI from "@/components/ui/SignatureI";
import SonicFieldFallback from "@/components/sonic-field/SonicFieldFallback";
import SonicWaveField from "@/components/sonic-field/SonicWaveField";
import VideoFacade from "@/components/media/VideoFacade";
import FounderCard from "@/components/team/FounderCard";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import SkipLink from "@/components/layout/SkipLink";
import { associations, capabilities, humanEvents, integration, machineEvents, technologyBehaviors } from "@/content/home";
import { people } from "@/content/people";
import { patentPortfolio, researchEcosystem, selectedPublications } from "@/content/research";

export default function Homepage() {
  return <><SkipLink /><SiteHeader /><main id="main-content">
    <section className="hero" aria-labelledby="hero-title"><Container className="hero__grid"><div className="hero__copy"><SectionLabel>SoniXense / 01</SectionLabel><h1 id="hero-title"><span>Beyond</span><em className="hero__vision-line" aria-label="Vision."><span aria-hidden="true">V<SignatureI />s<SignatureI />on.</span></em></h1><p className="hero__tagline">Empowering experiences through intelligent sonic innovation.</p><p className="hero__intro">SoniXense transforms complex information into intuitive auditory experiences that extend human perception beyond visual-only interfaces.</p><div className="button-row"><ButtonLink href="#insight">Experience SoniXense</ButtonLink><ButtonLink href="#technology" secondary>Discover the technology</ButtonLink></div></div><div className="hero__visual"><SonicWaveField /></div></Container></section>

    <section className="section problem" aria-labelledby="problem-title"><Container><SectionLabel>Machine pace / 02</SectionLabel><div className="problem__statements"><h2 id="problem-title">Machines perceive more.</h2><p>Machines move at machine pace.</p><strong>Humans still decide.</strong></div><p className="problem__copy">Sensors, imaging, tracking, computation, AI inference, robotics, simulation, and automated systems can acquire and update information at a fundamentally different pace from human perception, integration, and decision-making.</p><div className="pace-visual" aria-label="Conceptual comparison of machine pace and human pace"><div className="pace-visual__machine"><p>Machine pace</p><ol>{machineEvents.map((event,index) => <li key={`${event}-${index}`}><span>{event}</span></li>)}</ol></div><div className="pace-visual__human"><p>Human pace</p><ol>{humanEvents.map((event) => <li key={event}><span>{event}</span></li>)}</ol></div></div></Container></section>

    <section id="insight" className="section insight" aria-labelledby="insight-title"><Container><SectionLabel>The insight / 03</SectionLabel><p className="display-question">What if information didn&apos;t have to compete for your eyes?</p><h2 id="insight-title">Hear what matters.</h2><p>SoniXense turns complex system information into meaningful auditory representations—an additional perceptual channel, rather than another screen.</p></Container></section>

    <section id="technology" className="section technology" aria-labelledby="technology-title"><Container><SectionLabel>The technology / 04</SectionLabel><div className="section-heading"><h2 id="technology-title">From complex data<br />to intuitive sonic perception.</h2><p>SoniXense Intelligence becomes part of an intelligent system, shaping information around human perception, context, and action.</p></div><div className="technology__layout"><div className="technology__modes">{technologyBehaviors.map((mode) => <article key={mode.name}><span>{mode.index}</span><div><h3>{mode.name}</h3><strong>{mode.lead}</strong><p>{mode.body}</p></div></article>)}</div><div className="technology__system"><SonicFieldFallback mode="intelligence" /><p className="technology__question">What can SoniXense do inside an intelligent system?</p></div></div></Container></section>

    <section className="section integration" aria-labelledby="integration-title"><Container><SectionLabel>Integration / 05</SectionLabel><div className="section-heading"><h2 id="integration-title">Built to integrate.</h2><p>SoniXense augments existing intelligent systems rather than asking teams to replace them. We augment. We don&apos;t replace.</p></div><div className="integration-map"><div className="integration-map__sources"><span>Sensors</span><span>Imaging</span><span>Tracking</span><span>AI</span><span>Digital twins</span><span>Robotics</span></div><div className="integration-map__core"><SonicFieldFallback mode="integration" /><strong>SoniXense</strong></div><div className="integration-map__result"><span>Existing interface</span><i>+</i><strong>Auditory intelligence</strong></div></div><div className="integration__path">{integration.map((item,index) => <article key={item.name}><span>0{index + 1}</span><h3>{item.name}</h3><p>{item.body}</p></article>)}</div></Container></section>

    <section id="surgery" className="section surgery" aria-labelledby="surgery-title"><Container><SectionLabel>Application / 01</SectionLabel><div className="surgery__heading"><div><h2 id="surgery-title">Surgery.</h2><p className="display-question">Our first frontier.</p></div><p>Modern surgery sees more than ever through imaging, navigation, robotics, and AI. Yet this information still competes for limited visual attention.</p></div><div className="surgery-placeholder" role="img" aria-label="Designed placeholder for a future image-guided surgery visual"><div className="surgery-placeholder__anatomy"><span /><span /><span /></div><div className="surgery-placeholder__tool" /><div className="surgery-placeholder__data"><span>Imaging</span><span>Tracking</span><span>AI context</span></div><p>Image-guided intervention visual<br /><small>Verified surgery imagery pending</small></p></div><p className="surgery__claim">SoniXense creates an integrated auditory perceptual channel, designed around human multisensory perception and cognition, so critical information can complement—not compete with—the user&apos;s existing sensory workflow.</p></Container></section>

    <section id="experience" className="section experience" aria-labelledby="experience-title"><Container><SectionLabel>Experience preview / 07</SectionLabel><div className="experience__grid"><div><h2 id="experience-title">Don&apos;t just see it.<br /><em>Hear it.</em></h2><p>Zoom into one concrete application: position, target, trajectory, and relationship. A later interactive experience will demonstrate how auditory navigation can communicate these dimensions.</p><VideoFacade provider="youtube" videoId="IuDm7Pg7I40" title="SoniXense surgical navigation film" /></div><div className="navigation-scene"><SonicFieldFallback mode="navigation" /><span className="navigation-scene__tool">Current position</span><span className="navigation-scene__target">Target</span><span className="navigation-scene__distance">Distance / relationship</span></div></div></Container></section>

    <section className="section capabilities" aria-labelledby="capabilities-title"><Container><SectionLabel>Auditory capabilities / 08</SectionLabel><div className="section-heading"><h2 id="capabilities-title">How auditory intelligence<br />manifests in interaction.</h2><p>One perceptual system; distinct interaction scenarios across monitoring, navigation, physical behavior, and intelligent-system awareness.</p></div><div className="capabilities__list">{capabilities.map((item,index) => <article key={item.name}><span>0{index + 1}</span><h3>{item.name}</h3><strong>{item.lead}</strong><p>{item.body}</p></article>)}</div></Container></section>

    <section className="section beyond" aria-labelledby="beyond-title"><Container><SectionLabel>Beyond surgery / 09</SectionLabel><h2 id="beyond-title">Surgery is our first frontier.<br /><em>Perception is the bigger question.</em></h2><div className="beyond__areas"><span>Exploring / Robotics</span><span>Exploring / XR + Spatial Computing</span><span>Exploring / Human–AI Interaction</span><span>Exploring / Complex Intelligent Systems</span></div><p>We also apply this sonification expertise to immersive art and experience design. <Link href="/artscience">Explore ArtScience →</Link></p></Container></section>

    <section id="company" className="section origin" aria-labelledby="origin-title"><Container><SectionLabel>Origin / Company / 10</SectionLabel><div className="origin__grid"><div><h2 id="origin-title">Research became technology.<br /><em>Technology is becoming SoniXense.</em></h2><p>SoniXense is a spin-off in formation emerging from the DFG-funded Synergia project and research at TUM&apos;s Chair for Computer Aided Medical Procedures &amp; Augmented Reality (CAMP).</p><div className="origin__links"><a href="https://synergia.camp.cit.tum.de/project/" target="_blank" rel="noopener noreferrer">Explore the Synergia project ↗</a><a href="https://www.cs.cit.tum.de/camp/start/" target="_blank" rel="noopener noreferrer">CAMP at TUM ↗</a></div></div><div className="origin__sequence"><span>Research</span><i>→</i><span>Technology</span><i>→</i><strong>Startup</strong></div></div></Container></section>

    <section id="team" className="section team" aria-labelledby="team-title"><Container><SectionLabel>Co-founders / 11</SectionLabel><div className="section-heading"><h2 id="team-title">Where technology meets<br />medicine and music.</h2><p>Founder-led and multidisciplinary: engineering, computation, medicine, perception, and artistic practice converge in one team.</p></div><div className="team__grid">{people.map((person,index) => <FounderCard key={person.id} person={person} index={index} />)}</div></Container></section>

    <section id="evidence" className="section evidence" aria-labelledby="evidence-title"><Container><SectionLabel>Scientific foundation / 12</SectionLabel><div className="section-heading"><h2 id="evidence-title">Research built this.</h2><p>The SoniXense vision is backed by years of research, international collaborations, patents, and awards.</p></div><div className="research-pillars"><article><SectionLabel>01 / Patent portfolio</SectionLabel><h3>{patentPortfolio.heading}</h3><p>{patentPortfolio.body}</p><p className="research-note">Selected public patent metadata pending approval.</p></article><article><SectionLabel>02 / Selected publications</SectionLabel>{selectedPublications.map((item) => <div className="publication" key={`${item.venue}-${item.year}`}><span>{item.year}</span><h3>{item.venue}</h3><p>{item.relevance}</p></div>)}<p className="research-note">Full titles, authors, and DOI links pending verified metadata.</p></article><article className="awards-evidence"><SectionLabel>03 / Awards</SectionLabel><h3>3× Sonification Award winner.</h3><div className="awards-evidence__images"><Image src="/images/founders/sasan-award.jpg" alt="Existing SoniXense award documentation" width={408} height={527} sizes="(max-width: 700px) 45vw, 260px" /><Image src="/images/founders/sasan-son-award.jpg" alt="Existing SoniXense award documentation" width={736} height={520} sizes="(max-width: 700px) 45vw, 260px" /></div><p className="research-note">Event and year captions pending verified details.</p></article><article><SectionLabel>04 / Research ecosystem</SectionLabel><div className="ecosystem-groups">{researchEcosystem.map((group) => <div key={group.category}><p>{group.category}</p><strong>{group.names.join(" · ")}</strong></div>)}</div></article></div><div className="association-row">{associations.map((item) => <div key={item.name}><Image src={item.image} alt={`${item.name} logo`} width={item.width} height={item.height} sizes="120px" /></div>)}</div></Container></section>

    <section id="contact" className="section final-cta" aria-labelledby="final-title"><Container className="final-cta__grid"><div><SectionLabel>SoniXense / 13</SectionLabel><h2 id="final-title">Beyond <em>Vision.</em></h2><p>Empowering experiences through intelligent sonic innovation.</p><div className="button-row"><ButtonLink href="mailto:sasan.matinfar@tum.de">Talk to SoniXense</ButtonLink><ButtonLink href="#technology" secondary>Explore the technology</ButtonLink></div></div><SonicFieldFallback mode="final" /></Container></section>
  </main><SiteFooter /></>;
}
